feat: added button component
imabhinavagarwal/ComponentLibrary pull request #16
Opened 2022-10-01 08:52 UTC by shraddha15-creator

Added Button component
- Primary button
- Button with link
- Rounded buttons

![btn-component](https://user-images.githubusercontent.com/66071175/193401478-75a624bd-5e17-4995-831a-7fff1233ef80.png)

2022-10-01 09:37 UTC, imabhinavagarwal requested changes
Please make changes as per the comment. Also, please help to update the Readme file with components and sub components you are adding

2022-10-01 09:37 UTC, imabhinavagarwal commented on components/components.html
> +  style="width: 930px; height: 564px; border:0; transform: scale(1); overflow:hidden;"
Please use this style in iframe to be in sync with rest
style="border:0; transform: scale(1); overflow:hidden;"

Also, please fix the indentation

2022-10-01 09:37 UTC, imabhinavagarwal commented on components/components.html
> +    </body>
Remove this tag from here. Body tag is closed at end of file after all the sections

2022-10-01 16:13 UTC, imabhinavagarwal commented on components/components.html
> +  style="width: 930px; height: 564px; border:0; transform: scale(1); overflow:hidden;"
@shraddha15-creator By fix the indentation, I meant just for the iframe tag 😅

2022-10-01 16:14 UTC, imabhinavagarwal commented
@shraddha15-creator Please resolve conflicts

2022-10-02 02:14 UTC, imabhinavagarwal approved these changes
There was duplicated code, just fixed that. Rest was okay

2022-10-02 02:15 UTC, merged

2022-10-02 05:03 UTC, shraddha15-creator commented
> There was duplicated code, just fixed that. Rest was okay

why did you not accept this pr for hacktoberfest?

2022-10-03 01:53 UTC, imabhinavagarwal commented
> > There was duplicated code, just fixed that. Rest was okay
> 
> why did you not accept this pr for hacktoberfest?

@shraddha15-creator I have marked it as hacktoberfest-accepted